### PR TITLE
added full credits parser

### PR DESCRIPTION
**Pull request by alberanid**

### CODE REVIEW

**Comment by alberanid** [comment]
Hi @apelord , was this working, or it was an aborted attempt?
Anyway, a separated parser for the full credits page make sense.

**Comment by apelord** [comment]
Hi @alberanid! As I remember it was working. I need to check it once again.

**Comment by alberanid** [comment]
Hi @apelord , don't worry: I made it work, but it needs some fixes (partially done), plus I need some time to rework the build_person function completely, since right now it's a mess.

Thanks!

**Comment by apelord** [comment]
Thank you!

**Pull request merged**
