### PR TITLE
Advanced search

### PR DESCRIPTION
**Pull request by uyar**
This PR adds a parser for the detailed title search page. It supports IMDb's sort criteria and also supports including adult titles. Adding more search criteria should be straightforward. Usage examples can be seen in the tests at the moment, the feature should be documented.

### CODE REVIEW

**Comment by uyar** [comment]
@aiberanid Can you take a look at this? I had to deal with some parts of the code where I don't feel very confident. The module proxies and object maps for example.

Failing tests aren't caused by these changes, as far as I can see.

**Comment by uyar** [comment]
Oh, now I remember that I forgot to escape title queries containing special symbols.

**Comment by uyar** [comment]
> Oh, now I remember that I forgot to escape title queries containing special symbols.

Fixed.

**Comment by alberanid** [comment]
merged, thanks!

**Pull request merged**
