### PR TITLE
Move configuration to pyproject.toml

### PR DESCRIPTION
**Pull request by uyar**
This PR introduces a pyproject.toml file (generated with poetry) instead of the various files like setup.py, requirements.txt, and MANIFEST.in. setup.cfg cannot be removed at the moment due to some tools (especially flake8) not supporting it. Other changes:

- Drop support claim for Python 2.7, 3.4 and 3.5.
- Remove get_movie, search_person and similar scripts for keeping the executable path uncluttered. These operations can be carried out using subcommands to the imdbpy script.
- The s32imdbpy and imdbpy2sql modules are moved to the imdb package and their scripts are generated as entry points.
- The setup script doesn't generate the i18n *.mo files anymore. These have to be generated manually before running "poetry build".
- Remove future imports for python2 support and source code coding declarations.
- Remove some obsolete keywords and classifiers from project metadata.

### CODE REVIEW

**Comment by alberanid** [comment]
that's cool, thanks!  I didn't know about poetry, and I've not followed very closely the development of Python, lately.

Some questions, before we can merge it.

## installation

I want to upgrade the documentation, since `setup.py` is gone.

What's the best way to do it now?

Is something like this okay?

```
# installation

First of all, install poetry following the instructions at https://python-poetry.org/

Then you can build and install IMDbPY with:
python imdb/locale/rebuildmo.py
poetry build
poetry install

If you want to open a virtualenv shell, you can run `poetry shell`

If you need to install it globally, run `pip install ./dist/imdbpy-*.whl`
```

## package maintainers

If they need support, what's the best way to explain what they need to do?

Maybe they can just use the built tar.gz (which contains a setup.py, I see)?

**Comment by uyar** [comment]
I use poetry in all my projects and I think it's really helpful but I'm not 100% sure that imdbpy needs it. That makes your review all the more important, feel free to reject it. Maybe we should ask others from the mailing list to test it out.

Upsides: Reduces the number of config files and `pyproject.toml` seems to be the way to go. Dependency management is easier. Downsides; `pip install -e .` or `python setup.py develop` don't work anymore (but this shouldn't be needed in most cases). I couldn't find a way of autogenerating `*.mo` files as part of the build process.

For the documentation part:

- You don't run `poetry build` for local development, just `poetry install`. `poetry build` will only generate the wheel and sdist packages under `dist`, it doesn't touch the development environment. `poetry install` creates a new virtual environment and installs everything into it.
- What do package managers usually work on? The repo sources or the source dist from pypi? If the latter, nothing changes. If the former, they will first need to run `poetry build`.

And one problem I couldn't solve yet: I get a unicode error when building the documents.

**Comment by uyar** [comment]
And one more note for the documentation: Commands have to be prefixed with poetry run, as in:

```
poetry run pytest tests
poetry run tox
poetry run flake8 imdb
```

This will make the commands run in the proper virtual environment, without having to activate it.

**Comment by uyar** [comment]
I'm not very comfortable with this PR. It mixes the move to pyproject.toml with the drop of Python 2. I'd like to separate these out and have a cleaner PR.

**Comment by alberanid** [comment]
I see, pardon if I had not the time for a proper review.  For sure dropping Python 2 can be done, since it's really time to switch to Python 3 for everyone. :)

Thanks!

**Comment by uyar** [comment]
> I see, pardon if I had not the time for a proper review. For sure dropping Python 2 can be done, since it's really time to switch to Python 3 for everyone. :)
> 
> Thanks!

No worries. Good thing you didn't, it needs a bit more thinking.

**Pull request closed without merging**
