### PR TITLE
grab poster from search

### PR DESCRIPTION
**Pull request by csweaver**
I've modified the searchMovieParser to grab the poser URL in addition to the id/info/akas. I've also added in a test for this functionality. I've tested locally under python 3.7.

LMK if there is anything else needed as far as testing/documentation go.

### CODE REVIEW

**Comment by uyar** [comment]
The xpath for selecting the `tr` looks a bit complicated to me. I can't test this for the moment but looking at the page, would something like `//td[@class="result_text"]/..` work to get to the parent `tr`? I'll leave this decision to @alberanid after my last seemingly innocent patch broke the build :)

Thanks for the offer on testing and documentation, they could both use improving. You can work on any part that is useful or interesting to you but if you would like a suggestion, the command-line interface scripts could be a starting point (see the end of #81 for example).

Adding features like in this PR or fixing stuff is definitely welcome too, obviously.

**Comment by alberanid** [comment]
hi @csweaver , thanks for the PR!

Right now the main problem is that it breaks the **search_person** method, since the imdb.parser.http.searchPersonParser.DOMHTMLSearchPersonParser class inherits from DOMHTMLSearchMovieParser.
To see it, you can run the **py.test** command on the original master and then on your branch.

Being somehow simple parsers I have no problems duplicating some code and make DOMHTMLSearchPersonParser inherit from DOMParserBase directly, but maybe it's possible to still use the same class for both.

Let me know if you want to work on it; otherwise I'll give it a look in the next days.

Thanks!

**Comment by csweaver** [comment]
@alberanid I should be able to fix the Person search tonight. I didn't realize it inherited from the movie search as well. 

@uyar The weird xpath is because the `tr` has two classes, `result_text` and `odd` or `even`. What I have looks for result_text as part of the string. I could make it an `OR`: `result_text odd | results_text even` but that might be more brittle if IMDB decides to change it. Your choice. 

Also, I think I was misunderstood about my doc/test offer. I'm happy to add docs or tests for this feature, but don't have enough time to contribute to this project overall :(. I do have a couple of other PRs in the works for imdbpy to support what I'm using your library for (provided they fit in with your vision for your project). 1) getting actor portraits from the full cast search and 2) getting episode counts from full cast search if the role was in a tv show.

**Comment by csweaver** [comment]
Ok, fixed the test by adding a property `img_type` to the class. I'm sure there are other ways to have done it, so let me know if you would prefer an alternative. There are still a few failing tests, but I checked the travis build and the same are failing in master, so I think we're good. 

The images that come back are the small thumbnails. Is there a util to convert the url to the original (or is that even desired?)?

**Comment by uyar** [comment]
@csweaver I see now what you meant by docs and testing. My mistake.

Personally, I prefer to avoid -if I can- using XPath functions like `concat` or `normalize-space` or `starts-with` in the hope that we can make lxml an optional dependency in the future. But they are being used in other parsers as well so that's not a problem.

You are right that it's tricky to match one of multiple classes. Just to be sure: You mean `findResult odd` and `findResult even`, right? Because the `td` with `result_text` doesn't have any other class, if I see correctly. In that case, I would prefer matching the `td` first and then going up to its parent using `..` like I suggested above: `//td[@class="result_text"]/..` You could even leave the `foreach` part as is (`//td[@class="result_text"]`) and start your photo path with a parent step (`../td[@class="primary_photo"]/a/img/@src`). That way you could get away without touching the other search parsers.

Anyway, I didn't have a chance to test these XPaths yet and I see that you have done some more work. So it's probably not worth dwelling over this if you have working code.

**Comment by csweaver** [comment]
Ahh, I missed the recommendation to keep the primary selector to the `result_text` class and use xpath to go to the parent. I should be able to test that out tonight.

**Comment by csweaver** [comment]
So I was definitely overly optimistic about my free time to get this done earlier, but I think I've got the XPath expression where you want it now. I went with this option. 
> You could even leave the foreach part as is (//td[@class="result_text"]) and start your photo path with a parent step (../td[@class="primary_photo"]/a/img/@src). That way you could get away without touching the other search parsers.

Good advice, it's been a long time since I've used XPath and I didn't realize I could use a parent selector.

I've pulled in your latest changes so the tests are all passing locally. Let me know any additional changes you need.

**Comment by alberanid** [comment]
@csweaver : that's great, thank you very much! I've added your name to the list of contributors.

To answer this:

> The images that come back are the small thumbnails. Is there a util to convert the url to the original (or is that even desired?)?

the full-size thumbnail can be retrieved calling the `get_fullsizeURL` method of Movie and Person objects.
If the thumbnail is present, some other keys should also be available (`'full-size cover url'` for movies and `'full-size headshot'` for persons) - but I have to admit I've not tested it in a long time.

**Comment by csweaver** [comment]
Thank you!

**Pull request merged**
