### PR TITLE
Add imdb list as a source

### PR DESCRIPTION
**Pull request by aapjeisbaas**
I was missing the way to pull in lists, so this is what I came up with.
Mostly I tried to look at what was already in place and extend it to suit my needs.

Should I place my own name in the top of `listParser.py `, I wasn't sure about this.

### CODE REVIEW

**Comment by aapjeisbaas** [comment]
This pull request fixes the public list part of #250 maybe I'll later try to implement the watchlist part of #250

**Comment by aapjeisbaas** [comment]
This only pulls in the first 100 items in a list, there is no pagination in place

**Comment by alberanid** [comment]
that's really cool, thanks!  Merged and added your name to the credits. (I've just changed the "list" variable name to "list_")

**Comment by aapjeisbaas** [comment]
Thanks for accepting this, the list to list_ is indeed a better idea.
If you're curious I use this package to power a serverless movie api.
blog: https://aapjeisbaas.nl/project/popular-movies/ 
project: https://gitlab.com/aapjeisbaas/popular-movies

**Comment by alberanid** [comment]
cool!  Thanks for the notice.

**Pull request merged**
