### PR TITLE
fixed the awards bugs in MovieParser.py

### PR DESCRIPTION
**Pull request by jason12360**
I found out that the imdbpy can not fetch awards information of the movie. I rewrote the DOMHTMLAwardsParser. So it can fetch the awards information

### CODE REVIEW

**Comment by jason12360** [comment]
There are 1316 actors in the test_http_movie_full_credit case , but the test assumption is 1315. This issue make my code build error.

**Comment by alberanid** [comment]
@jason12360 : thanks a lot, I've added your name to the credits!

**Comment by vlyalcin** [comment]
I think this problem still occurs.

IMDbPY==6.9.dev20200301

```
from imdb import IMDb

# create an instance of the IMDb class
ia = IMDb()

# get a movie
movie = ia.get_movie('0133093')

#get awards from movie object
movie['awards']
```

`
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/volkan/PycharmProjects/imdb-new-version-test/lib/python3.6/site-packages/imdb/utils.py", line 1503, in __getitem__
    rawData = self.data[key]
KeyError: 'awards'
`

**Comment by vlyalcin** [comment]
Sorry, the way that I bring the awards was not correct. I needed to give the "info" parameter to get_movie method. Here is the correct way:

`from imdb import IMDb

# create an instance of the IMDb class
ia = IMDb()

# get a movie
movie = ia.get_movie('0133093', info=['awards'])

#get awards from movie object
movie['awards']`

**Pull request merged**
