### PR TITLE
Imdbpy legacy redesign backport

### PR DESCRIPTION
**Pull request by MasterMind2k**
I've backported IMDb redesign patches from #103 to legacy branch.

# Steps taken
  1. Identify beginning of the patches
  2. Used `git rev-list --reverse <commit_id>..master -- imdb/parser/http | git cherry-pick --stdin`
  3. In first commit I saw very large conflicts
  4. Searched for PEP8 related commits
  5. Cherry-picked PEP8 related commits
  6. Redone the second step
  7. When looking at conflicts, I've taken extra care at `u` prefixes and `str/unicode` functions
  8. Any special change I have documented in commit message

Hope this helps to anyone. But since, the legacy branch does not have any tests, this patch is likely going to be a cowboy ride on production :).

I've also decided to cherry-pick every commit as-is for easier review (if I've missed something solving the conflicts).

### CODE REVIEW

**Comment by alberanid** [comment]
@MasterMind2k : thanks a lot, very cool!  But yes, with no test suite is a little risky to merge it immediately.

If someone has some time to test it (at least the major features), let us know.

**Comment by MasterMind2k** [comment]
Another option would be, to backport tests?

Otherwise, at Podnapisi.NET is being used without any serious implications. But we use only a subset (genres, title, year, poster, countries) of features.

I could try to backport the tests next weekend. Other way (perhaps better) would be to re-support Python 2.7? What is the biggest problem to have a compatibility with Python 2.7?

**Comment by alberanid** [comment]
hi @MasterMind2k , the biggest problems were lack of experience and time to devote to the task. :-)
Supporting both Python 2.7 and Python 3.x seems a lot of work and I'm not sure it's worth it, since Python 2.7 will go in end of life in a couple of years.

Backporting the test suite to 2.7 would be cool; I'm not sure if there are some reason for not doing it.  Probably @uyar knows better than me if there are reasons for not doing it.

Thanks for your help!

**Comment by uyar** [comment]
I've copied the tests from the master branch to the legacy branch. Tests don't use anything Py3-specific. The only problem was that the movie reviews parser is not backported to legacy, so I've removed its tests. Other than that, this PR seems to fix most problems in the movie combined parser. Before applying it I had 83 errors, after applying it I get 25 errors.

**Comment by alberanid** [comment]
ok, if there are no objections in the next few hours, I'll squash and merge this PR. :-)

**Comment by uyar** [comment]
I think merging it is OK.

**Pull request merged**
