### PR TITLE
New "person awards" parser was implemented #234

### PR DESCRIPTION
**Pull request by vlyalcin**
Person and movie parser was using the same/common parser. Now they are separated.

### CODE REVIEW

**Comment by alberanid** [comment]
Thanks! I'll try to review it as soon as possible, but it may take a few days: I'm moving my house. :-)

Two questions:

1. Have you tried this parser on movie awards? Are they much different?

2. Why "movie1" and "movie2"? Is this the maximum number of movies that may be present?

**Comment by vlyalcin** [comment]
Hi @alberanid ,

Thank you too. Take your time. There's no rush to reviewing the code :)

1. I didn't have the chance to compare deeply yet.
2. It is about candidates who join awards with multiple films.
So it means one actor should play in multiple films and these multiple films should be nominated at the same awards in the same year. I thought it is not a very common case and two movies are enough.

But I think the proper way to solve this case is handling at the code side.

So I have a question in this point:

Instead of defining two separate movie keys, like below, how can we get the list of text of the "a" elements?

```
                    Rule(
                        key='movie1',
                        extractor=Path('./td[@class="award_description"]/a[1]/text()')
                    ),
                    Rule(
                        key='movie2',
                        extractor=Path('./td[@class="award_description"]/a[2]/text()')
                    ),
```

Is there a way to return list from the below rule? 
I get error if I use below rule: TypeError: sequence item 0: expected str instance, HtmlElement found

```
                    Rule(
                        key='mov',
                        extractor=Path('./td[@class="award_description"]/a')
                    ),
```

**Comment by vlyalcin** [comment]
By the way, I have some notes:
- In no awards cases, code raises "key" error. Is that expected behaving?
- I saw that x.get('category') already returns None if the key does not exist, so I don't have to specify like x.get('category', None) to get none (I should edit the part I coded).

**Comment by vlyalcin** [comment]
Hi again,

I think I solved the second case we talked above. I will send a new pull request.

```
Rule(
    key='movies',
    extractor=Path(
        foreach='./td[@class="award_description"]/a',
        path='./text()'
    )
)
```

Sorry for floods :)
Thanks.

**Comment by alberanid** [comment]
merged!

I've also the creation of Movie objects (instead of just the title strings) and entries for the Shared With list.

It's probably not perfect, but that HTML is partially broken and really difficult to parse correctly.

Thanks a lot, I've added your name to the credits.

**Pull request merged**
