### PR TITLE
helpers.resizeImage

### PR DESCRIPTION
**Pull request by GrbavaCigla**
https://github.com/alberanid/imdbpy/issues/265

### CODE REVIEW

**Comment by alberanid** [comment]
that's great, thanks!

As proposed in my commit, I've just split width and height parameters.  Is it okay with you?

**Comment by GrbavaCigla** [comment]
Ofcorse

**Comment by GrbavaCigla** [comment]
And I wanted to ask, why do you use camel case in helpers?

**Comment by alberanid** [comment]
that's great, thanks!

As proposed in my commit, I've just split width and height parameters.  Is it okay with you?

> And I wanted to ask, why do you use camel case in helpers?

No real reason, it happened.
It's not nice that it's no coherent with the rest of the API, but probably it's not worth the trouble to fix it, now.

**Pull request merged**
